// <auto-generated />
using System;
using DebtManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DebtManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314105335_InitKalkulator")]
    partial class InitKalkulator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DebtManager.Models.Dlug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("Czestotliwosc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPierwszejRaty")
                        .HasColumnType("TEXT");

                    b.Property<int>("DzienRaty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("InnaCzestotliwoscDni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiczbaRat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Oprocentowanie")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypRat")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WartoscPoczatkowa")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WyrownanieWPierwszejRacie")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dlugi");
                });

            modelBuilder.Entity("DebtManager.Models.Nadplata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CzescOdsetkowa")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CzyEdytowanaRecznie")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("DlugId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Efekt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kwota")
                        .HasColumnType("TEXT");

                    b.Property<int>("Typ")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DlugId");

                    b.ToTable("Nadplaty");
                });

            modelBuilder.Entity("DebtManager.Models.Rata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyEdytowanaRecznie")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyOplacona")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRaty")
                        .HasColumnType("TEXT");

                    b.Property<int>("DlugId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kapital")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumerRaty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Odsetki")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OprocentowanieRaty")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PozostaloKapitalu")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DlugId");

                    b.ToTable("Raty");
                });

            modelBuilder.Entity("DebtManager.Models.ZmianaOprocentowania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataZmiany")
                        .HasColumnType("TEXT");

                    b.Property<int>("DlugId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NoweOprocentowanie")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DlugId");

                    b.ToTable("ZmianyOprocentowania");
                });

            modelBuilder.Entity("DebtManager.Models.Nadplata", b =>
                {
                    b.HasOne("DebtManager.Models.Dlug", null)
                        .WithMany("Nadplaty")
                        .HasForeignKey("DlugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DebtManager.Models.Rata", b =>
                {
                    b.HasOne("DebtManager.Models.Dlug", "Dlug")
                        .WithMany("Raty")
                        .HasForeignKey("DlugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dlug");
                });

            modelBuilder.Entity("DebtManager.Models.ZmianaOprocentowania", b =>
                {
                    b.HasOne("DebtManager.Models.Dlug", null)
                        .WithMany("ZmianyOprocentowania")
                        .HasForeignKey("DlugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DebtManager.Models.Dlug", b =>
                {
                    b.Navigation("Nadplaty");

                    b.Navigation("Raty");

                    b.Navigation("ZmianyOprocentowania");
                });
#pragma warning restore 612, 618
        }
    }
}
